/**
 * Downloads the two project fonts from Google Fonts into assets/fonts/ and
 * writes src/styles/fonts.css pointing at the local files.
 *
 * Run once with `npm run fonts`. The files are committed, so a build never
 * needs the network (launch checklist: "Fonts self-hosted inside the build").
 * Only the latin subset is kept; the game's text is English.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'assets', 'fonts');

// A modern desktop UA gets woff2; an unknown UA gets a much larger ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** @type {{ file: string, css: string, family: string, weight: number }[]} */
const WANTED = [
  { file: 'bungee-400.woff2', css: 'family=Bungee', family: 'Bungee', weight: 400 },
  {
    file: 'atkinson-400.woff2',
    css: 'family=Atkinson+Hyperlegible:wght@400;700',
    family: 'Atkinson Hyperlegible',
    weight: 400,
  },
  {
    file: 'atkinson-700.woff2',
    css: 'family=Atkinson+Hyperlegible:wght@400;700',
    family: 'Atkinson Hyperlegible',
    weight: 700,
  },
];

/** Pulls the latin-subset src url for one weight out of a Google Fonts stylesheet. */
function latinUrl(css, weight) {
  const blocks = css.split('@font-face').slice(1);
  for (const block of blocks) {
    const isWeight = new RegExp(`font-weight:\\s*${weight};`).test(block);
    // The latin block is the one whose unicode-range starts at U+0000.
    const isLatin = /unicode-range:\s*U\+0000/.test(block);
    if (isWeight && isLatin) return block.match(/url\((https:[^)]+)\)/)?.[1];
  }
  return undefined;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const sheets = new Map();

  for (const want of WANTED) {
    if (!sheets.has(want.css)) {
      const res = await fetch(`https://fonts.googleapis.com/css2?${want.css}&display=swap`, {
        headers: { 'User-Agent': UA },
      });
      if (!res.ok) throw new Error(`Google Fonts said ${res.status} for ${want.css}`);
      sheets.set(want.css, await res.text());
    }
    const url = latinUrl(sheets.get(want.css), want.weight);
    if (!url) throw new Error(`No latin woff2 for ${want.family} ${want.weight}`);
    const font = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!font.ok) throw new Error(`Font download failed: ${url}`);
    const bytes = Buffer.from(await font.arrayBuffer());
    await writeFile(join(FONT_DIR, want.file), bytes);
    console.log(`  ${want.file}  ${(bytes.length / 1024).toFixed(1)} KB`);
  }

  const face = (family, weight, file) =>
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${weight};\n` +
    `  font-display: block;\n` +
    `  src: url('../../assets/fonts/${file}') format('woff2');\n` +
    `}\n`;

  const css =
    `/* Generated by tools/fetch-fonts.js. Do not edit by hand. */\n` +
    WANTED.map((w) => face(w.family, w.weight, w.file)).join('\n');
  await writeFile(join(ROOT, 'src', 'styles', 'fonts.css'), css);
  console.log('  src/styles/fonts.css written');
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
